name: MultiFun
version: '${project.version}'
main: me.capitainecat0.multifun.MultiFun
api-version: 1.13
authors: [ CapitaineCat0 ]
description: Plugin fun de la série Multi
website: https://hallofgames.fr/plugins
commands:
  hat:
    description: Permet de placer un item sur votre tête
  leporte:
    description: Permet d'obtenir une porte mystére
  lightning:
    description: Permet d'obtenir un bâton divin
